services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend:
      image: node:16
      working_dir: /usr/src/app
      volumes:
        - ./backend:/usr/src/app
      ports:
        - "5000:5000"
      command: ["npm", "start"]
